### ISSUE TITLE
New system distributions

### ISSUE THREAD

**Issue by elcomtik** [mrlesmithjr/dockerfiles#38]
**Is your feature request related to a problem? Please describe.**
I would like to add new distributions, namely Fedora36 & Rocky9

**Describe the solution you'd like**
I will make PR, would you mind adding the label "hacktoberfest" to this project?

**Comment by elcomtik** [comment]
> I will make PR, would you mind adding the label "hacktoberfest" to this project?

@mrlesmithjr

**Comment by mrlesmithjr** [comment]
done
